[server]
udp_listen = "0.0.0.0:5353"
tcp_listen = "0.0.0.0:5353"
dot_listen = "0.0.0.0:8853"
doh_listen = "0.0.0.0:8443"

[tls]
cert_pem = "tls/server.crt"
key_pem = "tls/server.key"

[balancing]
algorithm = "round_robin"

[security]
deny_any = true
deny_dnskey = true
request_timeout_ms = 1500

[cache]
enabled = true
max_size = 20000
ttl_seconds = 600

[metrics]
listen = "127.0.0.1:9100"

[hosts_local]
# "example.com." = "1.2.3.4"

[plugins]
libraries = [
    "plugins/remote-hosts-plugin/target/debug/libbalancedns_remote_hosts_plugin.dylib",
]

[[upstreams]]
name = "yandex-ru-udp"
proto = "udp"
addr = "77.88.8.8:53"
pool = "default"
weight = 1

[[upstreams]]
name = "cloudflare-udp"
proto = "udp"
addr = "1.1.1.1:53"
pool = "default"
weight = 5

[[upstreams]]
name = "google-udp"
proto = "udp"
addr = "8.8.8.8:53"
pool = "default"
weight = 5

[[upstreams]]
name = "cloudflare-doh-fallback"
proto = "doh"
url = "https://1.1.1.1/dns-query"
pool = "default"
weight = 1

[[routing_rules]]
suffix = ".ru."
upstreams = ["yandex-ru-udp"]

[[routing_rules]]
suffix = "."
upstreams = ["cloudflare-udp", "google-udp", "cloudflare-doh-fallback"]
